export const styles = {
  tnrB16: {
    fontFamily: "Times New Roman, Times, serif",
    fontWeight: "bold",
    fontSize: "16.2pt",
    lineHeight: 1,
  },
  hvN1012: {
    fontFamily: "hnr",
    fontWeight: "normal",
    fontSize: "9pt",
    lineHeight: "12pt",
  },
  cbB10: {
    fontFamily: "Calibri Bold",
    fontWeight: "bold",
    fontSize: "10pt",
  },
  cbB11: {
    fontFamily: "Calibri Bold",
    fontWeight: "bold",
    fontSize: "11pt",
  },
  cbB13: {
    fontFamily: "Calibri Bold",
    fontWeight: "bold",
    fontSize: "13pt",
  },
  cbB12: {
    fontFamily: "Calibri Bold",
    fontWeight: "bold",
    fontSize: "12pt",
  },
  cbB14: {
    fontFamily: "Calibri Bold",
    fontWeight: "bold",
    fontSize: "14pt",
  },
  cbB15: {
    fontFamily: "Calibri Bold",
    fontWeight: "bold",
    fontSize: "15pt",
  },
  cbB16: {
    fontFamily: "Calibri Bold",
    fontWeight: "bold",
    fontSize: "16pt",
  },
  cbB1010: {
    fontFamily: "Calibri Bold",
    fontWeight: "bold",
    fontSize: "10.5pt",
    lineHeight: "10.5pt",
  },
  cbB1214: {
    fontFamily: "Calibri Bold",
    fontWeight: "bold",
    fontSize: "12pt",
    lineHeight: "14pt",
  },
  cbB0909: {
    fontFamily: "Calibri Bold",
    fontWeight: "bold",
    fontSize: "9.5pt",
    lineHeight: "9.5pt",
  },
  cbR1010: {
    fontFamily: "Calibri Regular",
    fontWeight: "normal",
    fontSize: "10.25pt",
    lineHeight: "9.5pt",
  },
  cbR1214: {
    fontFamily: "Calibri Regular",
    fontWeight: "normal",
    fontSize: "12pt",
    lineHeight: "13.5pt",
  },
  cbR1216: {
    fontFamily: "Calibri Regular",
    fontWeight: "normal",
    fontSize: "12pt",
    lineHeight: "15pt",
  },
  cbR1218: {
    fontFamily: "Calibri Regular",
    fontWeight: "normal",
    fontSize: "12.11pt",
    lineHeight: "15pt",
  },
  cbR1219: {
    fontFamily: "Calibri Regular",
    fontWeight: "normal",
    fontSize: "12pt",
    lineHeight: "17pt",
  },
  cbR1227: {
    fontFamily: "Calibri Regular",
    fontWeight: "normal",
    fontSize: "12.5pt",
    lineHeight: "27pt",
  },
  cbR1112: {
    fontFamily: "Calibri Regular",
    fontWeight: "normal",
    fontSize: "11pt",
    lineHeight: "12pt",
  },
  cbR1012: {
    fontFamily: "Calibri Regular",
    fontWeight: "normal",
    fontSize: "10pt",
    lineHeight: "12pt",
  },
  cbR0608: {
    fontFamily: "Calibri Regular",
    fontWeight: "normal",
    fontSize: "6pt",
    lineHeight: "8pt",
  },
  gsBB12: {
    fontFamily: "Grafolita Script",
    fontWeight: "bold",
    fontSize: "12pt",
  },
};
